# config/config.yml

# Settings for the source Wikimedia API
wikimedia:
  base_url: "https://dumps.wikimedia.org/other/pageviews"

spark: {}

# Local data storage paths
data:
  pageviews_path: "data/pageviews"
  processed_path: "data/processed"

# --- Real-time Streaming Configuration ---
# Settings for the Kafka cluster
kafka:
  bootstrap_servers: "localhost:9092"
  topic: "wikimedia_events"
  consumer_group_id: "wikimedia-data-consumer-group"

# Settings for the Snowflake Data Warehouse (for a future phase)
snowflake:
  database: "WIKIMEDIA"
  schema: "RAW"
  warehouse: "COMPUTE_WH"